import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Inter } from "next/font/google";

import { BASE_URL } from "@/constants";
import { AppWrapper } from "@/components/AppWrapper";

import "@/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res = await fetch(`${BASE_URL}/api/auth/check`, {
    headers: {
      "Content-Type": "application/json",
      Cookie: cookies().toString(),
    },
  });

  const userData = (await res.json()).data as IUserData;

  return (
    <html lang="en">
      <body className="bg-mainGrey">
        <AppWrapper userData={userData}>{children}</AppWrapper>
      </body>
    </html>
  );
}
