import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { BASE_URL } from "@/constants";
import serverRequest from "@/utils/serverRequest";
import { AppWrapper } from "@/components/AppWrapper";

import "@/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userData = await serverRequest<IUserData>(`${BASE_URL}/api/auth/check`);

  return (
    <html lang="en">
      <body className="bg-mainGrey">
        <AppWrapper userData={userData}>{children}</AppWrapper>
      </body>
    </html>
  );
}
